// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fezdvaebwlembydypqim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlemR2YWVid2xlbWJ5ZHlwcWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTU2OTksImV4cCI6MjA3NDU3MTY5OX0.yT6gv872FDDIA7Vg-6pmwwcK2m8A2Cdhe2YS6fEqIiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});